-- 	CREATE USER --

--CREATE USER AVIACAO IDENTIFIED BY oracle;
--GRANT CONNECT TO AVIACAO;
--GRANT CONNECT, RESOURCE, DBA TO VEM_SER;
--GRANT CREATE SESSION TO AVIACAO;
--GRANT DBA TO AVIACAO;
--GRANT CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE TO AVIACAO;
--GRANT CREATE MATERIALIZED VIEW TO AVIACAO;
--GRANT GLOBAL QUERY REWRITE TO AVIACAO;
--GRANT SELECT ANY TABLE TO AVIACAO;

-- CLEAN EVERYTHING IF NEEDED --
--DROP TABLE AVIACAO.VENDA;
--DROP TABLE AVIACAO.PASSAGEM;
--DROP TABLE AVIACAO.TRECHO;
--DROP TABLE AVIACAO.COMPANHIA;
--DROP TABLE AVIACAO.COMPRADOR;
--DROP TABLE AVIACAO.USUARIO;
--DROP SEQUENCE AVIACAO.seq_usuario;
--DROP SEQUENCE AVIACAO.seq_passagem;
--DROP SEQUENCE AVIACAO.seq_trecho;
--DROP SEQUENCE AVIACAO.seq_venda;

 -- CREATE TABLES --

CREATE TABLE AVIACAO.USUARIO (
  id_usuario NUMBER,
  login VARCHAR2(100) UNIQUE NOT NULL,
  senha VARCHAR2(20) NOT NULL,
  nome VARCHAR2(100) NOT NULL,
  tipo VARCHAR2(20) NOT NULL,
  ativo NUMBER(1) NOT NULL,
  PRIMARY KEY (id_usuario)
);

CREATE TABLE AVIACAO.COMPRADOR (
  cpf CHAR(14) UNIQUE NOT NULL,
  id_usuario number(10,0) NOT NULL,
  PRIMARY KEY (id_usuario),
  CONSTRAINT FK_COMPRADOR_ID_USUARIO FOREIGN KEY (id_usuario) REFERENCES USUARIO(id_usuario)
);

CREATE TABLE AVIACAO.COMPANHIA (
  cnpj CHAR(18) UNIQUE NOT NULL,
  nome_fantasia VARCHAR2(100) NOT NULL,
  id_usuario number(10,0) NOT NULL,
  PRIMARY KEY (id_usuario),
  CONSTRAINT FK_COMPANHIA_ID_USUARIO FOREIGN KEY (id_usuario) REFERENCES USUARIO(id_usuario)
);

CREATE TABLE AVIACAO.AVIAO(
	id_aviao NUMBER,
	codigo_aviao VARCHAR(20) UNIQUE NOT NULL,
	capacidade NUMBER NOT NULL,
	ultima_manutencao DATE NOT NULL,
	id_companhia NUMBER,
	PRIMARY KEY (id_aviao),
	CONSTRAINT FK_AVIAO_COMPANHIA FOREIGN KEY (id_companhia) REFERENCES COMPANHIA(id_usuario)
);

CREATE TABLE AVIACAO.VOO(
	id_voo NUMBER,
	origem VARCHAR2(20) NOT NULL,
	destino VARCHAR2(20) NOT NULL,
	data_partida TIMESTAMP NOT NULL,
	data_chegada TIMESTAMP NOT NULL,
	assentos_disponiveis NUMBER(3) NOT NULL,
	id_aviao NUMBER,
	PRIMARY KEY (id_voo),
	CONSTRAINT FK_VOO_ID_AVIAO FOREIGN KEY (id_aviao) REFERENCES AVIAO(id_aviao)
);


CREATE TABLE AVIACAO.PASSAGEM (
  id_passagem NUMBER,
  codigo VARCHAR2(36) UNIQUE NOT NULL,
  status NUMBER(1) NOT NULL,
  valor NUMBER(19,4) NOT NULL,
  numero_assento CHAR(2) NOT NULL,
  tipo_assento NUMBER(1) NOT NULL,
  id_companhia NUMBER NOT NULL,
  id_venda NUMBER,
  id_voo NUMBER NOT NULL,
  PRIMARY KEY (id_passagem),
  CONSTRAINT FK_PASSAGEM_ID_COMPANHIA FOREIGN KEY (id_companhia) REFERENCES COMPANHIA(id_usuario),
  CONSTRAINT FK_PASSAGEM_ID_VOO FOREIGN KEY (id_voo) REFERENCES VOO(id_voo),
  CONSTRAINT UNQ_PASSAGEM_NUMERO_ASSENTO UNIQUE (id_voo, numero_assento)
 );

CREATE TABLE AVIACAO.VENDA (
  id_venda NUMBER,
  codigo VARCHAR2(36) UNIQUE NOT NULL,
  status NUMBER(1) NOT NULL,
  data TIMESTAMP NOT NULL,
  id_companhia NUMBER NOT NULL,
  id_comprador NUMBER NOT NULL,
  id_passagem NUMBER NOT NULL,
  PRIMARY KEY (id_venda),
  CONSTRAINT FK_VENDA_ID_COMPRADOR FOREIGN KEY (id_comprador) REFERENCES COMPRADOR(id_usuario),
  CONSTRAINT FK_VENDA_ID_COMPANHIA FOREIGN KEY (id_companhia) REFERENCES COMPANHIA(id_usuario),
  CONSTRAINT FK_VENDA_ID_PASSAGEM FOREIGN KEY (id_passagem) REFERENCES PASSAGEM(id_passagem)
);

ALTER TABLE AVIACAO.PASSAGEM
ADD CONSTRAINT FK_PASSAGEM_ID_VENDA
FOREIGN KEY (id_venda) REFERENCES VENDA(id_venda); 

-- SEQUENCES --

CREATE SEQUENCE AVIACAO.seq_usuario
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE AVIACAO.seq_voo
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE AVIACAO.seq_passagem
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE AVIACAO.seq_venda
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE AVIACAO.seq_aviao
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

